### ISSUE TITLE
Sprint 1 - Update README to add backend technologies and approach

### ISSUE THREAD

**Issue by jaydhanani99** [karmakarvishal/Spirit-Soen6011summer2023#2]
Update README and add the following information:

- Overall project approach at the backend side
- Database technology
- Backend library/framework
- Authentication
- File upload (Specifically resume upload)
- Role-based authorization
- High level APIs requirements

**Comment by karmakarvishal** [comment]
## Project Overview

This project aims to develop a Career Services Application with a backend system using MySQL as the database technology. The backend is responsible for handling data storage, authentication, file uploads (specifically resume uploads), role-based authorization, and exposing high-level APIs for the frontend. The frontend technologies used in this project include AngularJS, JavaScript, and jQuery.

### Overall Project Approach at the Backend Side

The backend of this Career Services Application follows a modular and scalable approach. It is built using modern web development principles and technologies, ensuring robustness, security, and maintainability. The backend architecture is designed to handle concurrent requests efficiently, allowing for a seamless user experience.

### Database Technology

The backend utilizes **MySQL** as the database technology to store and manage data related to user profiles, job listings, connections, and more. MySQL is a reliable and widely-used relational database management system that offers robust data handling capabilities, transaction support, and scalability.

### Backend Library/Framework

To streamline the development process and enhance the functionality of the backend, the project incorporates the **Express.js** framework. Express.js is a fast and minimalist web application framework for Node.js. It provides a range of features and middleware that simplify routing, request handling, and response management, making it an ideal choice for building RESTful APIs.

### Authentication

To ensure secure access to the Career Services Application, the backend employs a robust authentication mechanism. It utilizes **JSON Web Tokens (JWT)** for user authentication. JWT is a stateless and secure method for transmitting information between parties as a JSON object. It enables the backend to verify the authenticity of requests and ensure that only authorized users can access protected resources.

### File Upload (Specifically Resume Upload)

The backend incorporates a file upload functionality, specifically for resume uploads. When users upload their resumes, the backend handles the process securely and efficiently. It utilizes a multipart form-data approach to receive and process file uploads. The uploaded resumes are then stored in a designated directory on the server or in a cloud storage service like **Amazon S3**.

### Role-Based Authorization

To control access to various features and resources within the Career Services Application, the backend implements a role-based authorization system. This system allows different users to have different levels of access based on their roles and permissions. The backend maintains a set of roles (such as "admin," "employer," and "job seeker") and associates them with specific permissions. Based on their assigned roles, users are granted or restricted access to certain functionalities.

### High-Level APIs Requirements

The backend exposes a set of high-level APIs to facilitate communication between the frontend and backend systems in the Career Services Application. These APIs enable the frontend, built using AngularJS, JavaScript, and jQuery, to perform various operations and interact with the backend effectively. Some of the high-level APIs requirements include:

1. User Management APIs: APIs for user registration, login, profile retrieval, and update.
2. File Upload APIs: APIs for handling resume uploads and associating them with user profiles.
3. Job Listings APIs: APIs for creating, retrieving, updating, and deleting job listings.
4. Connection APIs: APIs for managing user connections, such as sending connection requests and accepting/rejecting them.
5. Search APIs: APIs for searching and filtering job listings and user profiles based on various criteria.
6. Authentication and Authorization APIs: APIs for user authentication and authorization checks.
7. Error Handling APIs: APIs to handle and return appropriate error messages and status codes.

These high-level APIs are designed to be intuitive, efficient, and well-documented, enabling seamless integration with the AngularJS, JavaScript, and jQuery frontend of the Career Services Application and smooth communication between the two systems.

**Comment by karmakarvishal** [comment]
I have updated the High Level Requirements and also checked the other points mentioned above.
