### ISSUE TITLE
Story #1 Employer - Job Offer Creation & Candidate Selection

### ISSUE THREAD

**Issue by jaydhanani99** [karmakarvishal/Spirit-Soen6011summer2023#3]
- As an employer, I want to be able to create a job offer, so that I can attract potential candidates for the position.
- I should be able to provide details such as job title, description, required qualifications, and desired experience.
- I should have the option to set a deadline for applications and specify any additional application requirements.
- I want to be able to review and select candidates who have applied to my job offers.
- I should be able to access the list of candidates who have applied, view their resumes, and evaluate their qualifications.
- I should have the ability to shortlist candidates for further consideration and schedule interviews with them.
- It is important that I can track the progress of each candidate throughout the selection process.

**Comment by karmakarvishal** [comment]
All the points are completed except:
It is important that I can track the progress of each candidate throughout the selection process.
I should have the option to set a deadline for applications and specify any additional application requirements.
