### ISSUE TITLE
Story #3 - Admin - Track Jobs

### ISSUE THREAD

**Issue by dneha1210** [karmakarvishal/Spirit-Soen6011summer2023#5]
- I want to be able to track the job postings created by employers and the applications submitted by candidates.
- I should have a centralized dashboard where I can view a list of all active job postings, along with relevant details such as the job title, employer name, and application deadline.
- I should be able to access detailed information about each application, including the candidate's name, contact details, and attached resume. This will enable me to effectively manage the application process, track the progress of each candidate, and take appropriate actions such as shortlisting or rejecting candidates based on the employer's preferences and requirements.

**Comment by sahrawatvinay** [comment]
All the above tasks relating to Admin role has been implemented and merged ot the main branch.
