### ISSUE TITLE
[Frontend] Create User Interface for Admin - related to User Story - 2

### ISSUE THREAD

**Issue by PriyeshBhalala105** [karmakarvishal/Spirit-Soen6011summer2023#69]
- Layout and Components: Implement the designed user interface using Angular components and layouts. Develop reusable components that can be utilized for different administrative functionalities.

- Navigation and Routing: Set up a clear and intuitive navigation system for administrators to switch between different administrative functionalities.

- Authentication and Authorization: Restrict access to the Admin UI to users having role ADMIN only.

- Data Retrieval and Display: Connect the Admin UI to appropriate backend APIs to fetch data related to administrative tasks.

**Comment by sahrawatvinay** [comment]
All the tasks related to admin functionality have been implemented.
