### ISSUE TITLE
Story #4 Student/Candidate

### ISSUE THREAD

**Issue by dneha1210** [karmakarvishal/Spirit-Soen6011summer2023#7]
- As a student, I should be able to create my profile on the portal.
- Once I created the profile I should be able to login into my student account and get access to all jobs posted
- As a student/candidate, I want to be able to browse job offers, so that I can find opportunities that match my skills and interests. 

> Once I find a suitable job offer, I should be able to view its details and apply for it by submitting my resume. 
> I should also receive confirmation of my application and be able to track the status of my applications.

**Comment by karmakarvishal** [comment]
This Story is Completed.
