### ISSUE TITLE
[Frontend] Create dashboard for job posting - User Story 3 

### ISSUE THREAD

**Issue by jaydhanani99** [karmakarvishal/Spirit-Soen6011summer2023#76]
- Layout and Components: Create a new component for the dashboard to display the job posting organized by company, jobs, and candidates who applied to them.
    - Add a view button for each candidate and job to see the details of the candidate and job. 
    - Provide an update status button for each job application (use the update status API of the backend).

- Navigation and Routing: Provide navigation to the dashboard link, and the admin should visit the dashboard once they logged in.

- Authentication and Authorization: Restrict access to the Admin UI to users having role ADMIN only.

- Data Retrieval and Display: To fetch the dashboard data, use the appropriate job list API created by the backend.

**Comment by sahrawatvinay** [comment]
All tasks related to admin dashboard are done.
