### ISSUE TITLE
Story #5 - Job Seeker/Student - Message the Employer directly

### ISSUE THREAD

**Issue by dneha1210** [karmakarvishal/Spirit-Soen6011summer2023#99]
- As a job seeker/student, I should be able to access a direct message feature. So that I can contact the employer directly.

> We can give a message icon on user profiles for both job seeker and the employer, with which they can communicate with each other via a direct connection.
> This can avoid the time to write an email and direct communication regarding a job posting can be made on the portal itself.
> We can add a message icon on the user profile

**Comment by jaydhanani99** [comment]
Not doing this feature, as we focused on automatic resume creation functionality.
